# DOT PRODUCT IN NUMPY

#### Specifically, there are two rules to consider in dot product in python:
#### 1.	If both vector “A” and vector “B” are 1-dimensional arrays, it is an inner product of vector (without complex conjugation).
#### 2.	If both vector “A” and vector “B” are 2-dimensional arrays, it is a matrix multiplication.
#### You can only multiply two matrices if the number of columns of the first matrix is equal to the number of rows of the second matrix.
#### If the shape of one matrix is (m*n) and the shape of the other one should be (n*t).


# DOT PRODUCT OF TWO MATRICES.

#### We can then go ahead and multiply 2 matrices, here is an example of a 1*1 matrix “A” multiply with 1*1 matrix “B”.
#### That is: A * B = C


**QUESTION**

$$ A = \begin{bmatrix}-1\\ 2\\ 3 \end{bmatrix} B = \begin{bmatrix}0 \\ 2 \\ 1 \end{bmatrix}=7 $$

**SOLUTION**

**STEP 1**
$$ \begin{bmatrix}(-1*0)+(2*2)+(3*1) \end{bmatrix} $$

**STEP 2:**   
$$
\begin{bmatrix}0+4+3\end{bmatrix} $$

**FINAL ANSWER**

$$
\begin{bmatrix}7\end{bmatrix} $$


Firstly, import the Numpy package in your workspace and then create a 2D matrix as explained in the example above 
or any other matrix structure you want to try it out. Then create a vector ensuring the number of rows being equal 
to the number of columns in the matrix.You can then use the “dot()” method in the matrix and vector. It will return the result vector for you as showen.
You can check out the entire notebook and play around with the code using.
Let’s code them using Numpy:


In [9]:
import numpy as np
#we are importing the library


In [11]:
a = np. array ([[-1, 2, 3]])
b = np. array([[-0, 2, 1]])
#we are using vector “a” and vector “b”

In [12]:
print(a)

[[-1  2  3]]


In [13]:
print(b)

[[0 2 1]]


In [14]:
np.inner(a, b)

array([[7]])

In [15]:
#we are finding the inner product